/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.universidad.gui.vista;

import com.universidad.gui.modelo.Empleado;
import com.universidad.gui.servicio.EmpleadoServicio;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alejandro
 */
public class GUIListEmpleados extends javax.swing.JFrame {

    private EmpleadoServicio<Empleado> empleadoServicio;

    /**
     * Creates new form GUIListEmpleados
     */
    public GUIListEmpleados(EmpleadoServicio<Empleado> empleadoServicio) {
        initComponents();
        this.empleadoServicio = empleadoServicio;
        setLocationRelativeTo(null);
        this.jPanelListEmpleado.setVisible(false);
        this.jPanelListEmpleado.setLayout(new BorderLayout());
        this.jPanelListEmpleado.add(new JScrollPane(jTableListEmpleados), BorderLayout.CENTER);
        JPanel panelBotones = new JPanel(new GridLayout());
        panelBotones.add(jButton1Salir);
        panelBotones.add(jButton2Mostrar);
        getContentPane().add(jPanelListEmpleado, BorderLayout.CENTER);
        getContentPane().add(panelBotones, BorderLayout.SOUTH);
    }

    public void mostrar() {
        this.jPanelListEmpleado.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelListEmpleado = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableListEmpleados = new javax.swing.JTable();
        jButton1Salir = new javax.swing.JButton();
        jButton2Mostrar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GUIListEmpleado");
        setMaximumSize(new java.awt.Dimension(495, 425));
        setMinimumSize(new java.awt.Dimension(495, 425));
        setResizable(false);

        jPanelListEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanelListEmpleado.setToolTipText("title");
        jPanelListEmpleado.setMaximumSize(new java.awt.Dimension(421, 351));
        jPanelListEmpleado.setMinimumSize(new java.awt.Dimension(421, 351));

        jTableListEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Documento", "Tipo", "Nombre", "Salario", "Estatus"
            }
        ));
        jScrollPane2.setViewportView(jTableListEmpleados);

        javax.swing.GroupLayout jPanelListEmpleadoLayout = new javax.swing.GroupLayout(jPanelListEmpleado);
        jPanelListEmpleado.setLayout(jPanelListEmpleadoLayout);
        jPanelListEmpleadoLayout.setHorizontalGroup(
            jPanelListEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelListEmpleadoLayout.setVerticalGroup(
            jPanelListEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelListEmpleado, java.awt.BorderLayout.CENTER);

        jButton1Salir.setText("Salir");
        jButton1Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Salir, java.awt.BorderLayout.PAGE_START);

        jButton2Mostrar.setText("Mostrar");
        jButton2Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2MostrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2Mostrar, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SalirActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1SalirActionPerformed

    private void jButton2MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2MostrarActionPerformed
        try {
            List<Empleado> empleados = empleadoServicio.mostrar();
            if (empleados.size() != 0) {
                mostrar();
                DefaultTableModel model = (DefaultTableModel) jTableListEmpleados.getModel();
                model.setRowCount(0);
                for (Empleado empleado : empleados) {
                    Object[] fila = {
                        empleado.getNoDoumento(),
                        empleado.getTipoDocumento(),
                        empleado.getNombre(),
                        empleado.getSalarioBase(),
                        empleado.getEstatus()
                    };
                    model.addRow(fila);
                }
            } else {
                JOptionPane.showMessageDialog(this, "La lista está vacía");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al mostrar los empleados: " + e.getMessage());
        }

    }//GEN-LAST:event_jButton2MostrarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUIListEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUIListEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUIListEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUIListEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUIListEmpleados().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Salir;
    private javax.swing.JButton jButton2Mostrar;
    private javax.swing.JPanel jPanelListEmpleado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableListEmpleados;
    // End of variables declaration//GEN-END:variables
}
