/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.universidad.gui.vista;


import com.universidad.gui.modelo.implementacion.Administrativo;
import com.universidad.gui.modelo.implementacion.ESerGen;
import com.universidad.gui.servicio.implementacion.EmpleadoServicio;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    
  
  private static GUIPrincipal instancia;
  private EmpleadoServicio<Administrativo> empleadoServicioAdministrativo;
  private EmpleadoServicio<ESerGen> empleadoServicioESerGen;
  
    private GUIPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        this.empleadoServicioAdministrativo = new EmpleadoServicio<>();
        this.empleadoServicioESerGen = new EmpleadoServicio<>();
    }

    public static GUIPrincipal getInstance(){
        
        if(instancia == null){
           instancia = new GUIPrincipal();
        }
            return instancia;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        jMenuItemGenerarReporte = new javax.swing.JMenuItem();
        menuAdministrativo = new javax.swing.JMenu();
        itemAddAdministrativo = new javax.swing.JMenuItem();
        jMenuItemSearchAdministrativo = new javax.swing.JMenuItem();
        jMenuItemListAdministrativos = new javax.swing.JMenuItem();
        jMenuItemUpdateAdministrativos = new javax.swing.JMenuItem();
        jMenuItemDeleteAdministrativo = new javax.swing.JMenuItem();
        jMenuItemBonificacion = new javax.swing.JMenuItem();
        jMenuESerGen = new javax.swing.JMenu();
        jMenuItemAddEmpleado = new javax.swing.JMenuItem();
        jMenuItemSearchEmpleado = new javax.swing.JMenuItem();
        jMenuItemListEmpleado = new javax.swing.JMenuItem();
        jMenuItemUpdateEmpleado = new javax.swing.JMenuItem();
        jMenuItemDeleteEmpleado = new javax.swing.JMenuItem();
        jMenuCalcularNomina = new javax.swing.JMenuItem();
        jMenuItemComanda = new javax.swing.JMenuItem();
        CrudComandas = new javax.swing.JMenu();
        jMenuItemCrearComanda = new javax.swing.JMenuItem();
        jMenuItemBuscarComanda = new javax.swing.JMenuItem();
        jMenuItemVerComandas = new javax.swing.JMenuItem();
        jMenuItemActualizarComanda = new javax.swing.JMenuItem();
        jMenuItemEliminarComanda = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        itemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crudnator v 1_0 By Ostos Software");

        menuArchivo.setText("Archivo");
        menuArchivo.setName("Menu Archivo"); // NOI18N

        jMenuItemGenerarReporte.setText("Generar Reporte");
        jMenuItemGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGenerarReporteActionPerformed(evt);
            }
        });
        menuArchivo.add(jMenuItemGenerarReporte);

        jMenuBar1.add(menuArchivo);

        menuAdministrativo.setText("Administrativo");
        menuAdministrativo.setName("Menu Empleado"); // NOI18N
        menuAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdministrativoActionPerformed(evt);
            }
        });

        itemAddAdministrativo.setText("Crear Administrativo");
        itemAddAdministrativo.setName("Opcion Add Empleado"); // NOI18N
        itemAddAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddAdministrativoActionPerformed(evt);
            }
        });
        menuAdministrativo.add(itemAddAdministrativo);

        jMenuItemSearchAdministrativo.setText("Buscar Administrativo");
        jMenuItemSearchAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSearchAdministrativoActionPerformed(evt);
            }
        });
        menuAdministrativo.add(jMenuItemSearchAdministrativo);

        jMenuItemListAdministrativos.setText("Ver Administrativos");
        jMenuItemListAdministrativos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListAdministrativosActionPerformed(evt);
            }
        });
        menuAdministrativo.add(jMenuItemListAdministrativos);

        jMenuItemUpdateAdministrativos.setText("Actualizar Administrativos");
        jMenuItemUpdateAdministrativos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUpdateAdministrativosActionPerformed(evt);
            }
        });
        menuAdministrativo.add(jMenuItemUpdateAdministrativos);

        jMenuItemDeleteAdministrativo.setText("Eliminar Administrativo");
        jMenuItemDeleteAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteAdministrativoActionPerformed(evt);
            }
        });
        menuAdministrativo.add(jMenuItemDeleteAdministrativo);

        jMenuItemBonificacion.setText("Calcular Nómina");
        jMenuItemBonificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBonificacionActionPerformed(evt);
            }
        });
        menuAdministrativo.add(jMenuItemBonificacion);

        jMenuBar1.add(menuAdministrativo);

        jMenuESerGen.setText("Servicios Generales");

        jMenuItemAddEmpleado.setText("Crear Empleado");
        jMenuItemAddEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddEmpleadoActionPerformed(evt);
            }
        });
        jMenuESerGen.add(jMenuItemAddEmpleado);

        jMenuItemSearchEmpleado.setText("Buscar Empleado");
        jMenuItemSearchEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSearchEmpleadoActionPerformed(evt);
            }
        });
        jMenuESerGen.add(jMenuItemSearchEmpleado);

        jMenuItemListEmpleado.setText("Ver Empleados");
        jMenuItemListEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListEmpleadoActionPerformed(evt);
            }
        });
        jMenuESerGen.add(jMenuItemListEmpleado);

        jMenuItemUpdateEmpleado.setText("Actualizar Empleado");
        jMenuItemUpdateEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUpdateEmpleadoActionPerformed(evt);
            }
        });
        jMenuESerGen.add(jMenuItemUpdateEmpleado);

        jMenuItemDeleteEmpleado.setText("Eliminar Empleado");
        jMenuItemDeleteEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteEmpleadoActionPerformed(evt);
            }
        });
        jMenuESerGen.add(jMenuItemDeleteEmpleado);

        jMenuCalcularNomina.setText("Calcular Nómina");
        jMenuCalcularNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCalcularNominaActionPerformed(evt);
            }
        });
        jMenuESerGen.add(jMenuCalcularNomina);

        jMenuItemComanda.setText("Crear Comanda");
        jMenuESerGen.add(jMenuItemComanda);

        jMenuBar1.add(jMenuESerGen);

        CrudComandas.setText("Comandas");

        jMenuItemCrearComanda.setText("Crear Comanda");
        CrudComandas.add(jMenuItemCrearComanda);

        jMenuItemBuscarComanda.setText("Buscar Comanda");
        CrudComandas.add(jMenuItemBuscarComanda);

        jMenuItemVerComandas.setText("Ver Comandas");
        CrudComandas.add(jMenuItemVerComandas);

        jMenuItemActualizarComanda.setText("Actualizar Comanda");
        CrudComandas.add(jMenuItemActualizarComanda);

        jMenuItemEliminarComanda.setText("Eliminar Comanda");
        CrudComandas.add(jMenuItemEliminarComanda);

        jMenuBar1.add(CrudComandas);

        menuAyuda.setText("Ayuda");
        menuAyuda.setName("Menu Ayuda"); // NOI18N

        itemAcercaDe.setText("Acerca de ...");
        itemAcercaDe.setName("Opcion Acerca de"); // NOI18N
        itemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(itemAcercaDe);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcercaDeActionPerformed
         JOptionPane.showMessageDialog(this, "Desarrollado por David Alejandro De los Reyes Ostos");
    }//GEN-LAST:event_itemAcercaDeActionPerformed

    private void itemAddAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddAdministrativoActionPerformed
        GUIAddAdministrativo gui = new GUIAddAdministrativo(this.empleadoServicioAdministrativo);
        gui.setVisible(true);
        
    }//GEN-LAST:event_itemAddAdministrativoActionPerformed

    private void jMenuItemSearchAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSearchAdministrativoActionPerformed
        GUISearchAdministrativoPorNoDocumento gui = new GUISearchAdministrativoPorNoDocumento(this.empleadoServicioAdministrativo);
        gui.setVisible(true);
       
    }//GEN-LAST:event_jMenuItemSearchAdministrativoActionPerformed

    private void jMenuItemListAdministrativosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListAdministrativosActionPerformed
        GUIListAdministrativos guiListEmpleados = new GUIListAdministrativos(this.empleadoServicioAdministrativo);
        guiListEmpleados.setVisible(true);
    }//GEN-LAST:event_jMenuItemListAdministrativosActionPerformed

    private void jMenuItemUpdateAdministrativosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUpdateAdministrativosActionPerformed
        GUIActualizarAdministrativo guiActualizarEmpleado = new GUIActualizarAdministrativo(this.empleadoServicioAdministrativo);
        guiActualizarEmpleado.setVisible(true);
    }//GEN-LAST:event_jMenuItemUpdateAdministrativosActionPerformed

    private void menuAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdministrativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAdministrativoActionPerformed

    private void jMenuItemDeleteAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteAdministrativoActionPerformed
        GUIEliminarAdministrativo guiEliminarEmpleado = new GUIEliminarAdministrativo(this.empleadoServicioAdministrativo);
        guiEliminarEmpleado.setVisible(true);
    }//GEN-LAST:event_jMenuItemDeleteAdministrativoActionPerformed

    private void jMenuItemGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGenerarReporteActionPerformed
        JOptionPane.showMessageDialog(this, "Proximamente");
    }//GEN-LAST:event_jMenuItemGenerarReporteActionPerformed

    private void jMenuItemAddEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddEmpleadoActionPerformed

        GUIAddESerGen gui = new GUIAddESerGen(empleadoServicioESerGen);
        gui.setVisible(true);

    }//GEN-LAST:event_jMenuItemAddEmpleadoActionPerformed

    private void jMenuItemListEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListEmpleadoActionPerformed
        GUIListESerGen gui = new GUIListESerGen(this.empleadoServicioESerGen);
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemListEmpleadoActionPerformed

    private void jMenuItemSearchEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSearchEmpleadoActionPerformed
        GUISearchESerGenPorNoDocumento gui = new GUISearchESerGenPorNoDocumento(this.empleadoServicioESerGen);
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemSearchEmpleadoActionPerformed

    private void jMenuItemUpdateEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUpdateEmpleadoActionPerformed
            GUIActualizarESerGen gui = new GUIActualizarESerGen(this.empleadoServicioESerGen);
            gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemUpdateEmpleadoActionPerformed

    private void jMenuItemBonificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBonificacionActionPerformed
        
        GUICalcularNominaAdministrativos gui = new GUICalcularNominaAdministrativos(empleadoServicioAdministrativo);
        gui.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemBonificacionActionPerformed

    private void jMenuCalcularNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCalcularNominaActionPerformed
        GUICalcularNominaESerGen gui = new GUICalcularNominaESerGen(empleadoServicioESerGen);
        gui.setVisible(true);
        
        
        
    }//GEN-LAST:event_jMenuCalcularNominaActionPerformed

    private void jMenuItemDeleteEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteEmpleadoActionPerformed
       GUIEliminarESerGen gui = new GUIEliminarESerGen(empleadoServicioESerGen);
       gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemDeleteEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu CrudComandas;
    private javax.swing.JMenuItem itemAcercaDe;
    private javax.swing.JMenuItem itemAddAdministrativo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCalcularNomina;
    private javax.swing.JMenu jMenuESerGen;
    private javax.swing.JMenuItem jMenuItemActualizarComanda;
    private javax.swing.JMenuItem jMenuItemAddEmpleado;
    private javax.swing.JMenuItem jMenuItemBonificacion;
    private javax.swing.JMenuItem jMenuItemBuscarComanda;
    private javax.swing.JMenuItem jMenuItemComanda;
    private javax.swing.JMenuItem jMenuItemCrearComanda;
    private javax.swing.JMenuItem jMenuItemDeleteAdministrativo;
    private javax.swing.JMenuItem jMenuItemDeleteEmpleado;
    private javax.swing.JMenuItem jMenuItemEliminarComanda;
    private javax.swing.JMenuItem jMenuItemGenerarReporte;
    private javax.swing.JMenuItem jMenuItemListAdministrativos;
    private javax.swing.JMenuItem jMenuItemListEmpleado;
    private javax.swing.JMenuItem jMenuItemSearchAdministrativo;
    private javax.swing.JMenuItem jMenuItemSearchEmpleado;
    private javax.swing.JMenuItem jMenuItemUpdateAdministrativos;
    private javax.swing.JMenuItem jMenuItemUpdateEmpleado;
    private javax.swing.JMenuItem jMenuItemVerComandas;
    private javax.swing.JMenu menuAdministrativo;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    // End of variables declaration//GEN-END:variables
}

