/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.universidad.gui.vista;

import com.universidad.gui.modelo.Empleado;
import com.universidad.gui.servicio.implementacion.EmpleadoServicio;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    
  private EmpleadoServicio<Empleado> empleadoServicio;
  
    public GUIPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        this.empleadoServicio = new EmpleadoServicio<>();
    }

    public EmpleadoServicio<Empleado> getEmpleadoServicio() {
        return empleadoServicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        jMenuItemGenerarReporte = new javax.swing.JMenuItem();
        menuEmpleado = new javax.swing.JMenu();
        itemAddEmpleado = new javax.swing.JMenuItem();
        jMenuItemSearchEmpleado = new javax.swing.JMenuItem();
        ListEmpleado = new javax.swing.JMenuItem();
        jMenuItemUpdateEmpleados = new javax.swing.JMenuItem();
        jMenuItemDeleteEmpleado = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        itemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        menuArchivo.setText("Archivo");
        menuArchivo.setName("Menu Archivo"); // NOI18N

        jMenuItemGenerarReporte.setText("Generar Reporte");
        jMenuItemGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGenerarReporteActionPerformed(evt);
            }
        });
        menuArchivo.add(jMenuItemGenerarReporte);

        jMenuBar1.add(menuArchivo);

        menuEmpleado.setText("Empleado");
        menuEmpleado.setName("Menu Empleado"); // NOI18N
        menuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpleadoActionPerformed(evt);
            }
        });

        itemAddEmpleado.setText("AddEmpleado");
        itemAddEmpleado.setName("Opcion Add Empleado"); // NOI18N
        itemAddEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddEmpleadoActionPerformed(evt);
            }
        });
        menuEmpleado.add(itemAddEmpleado);

        jMenuItemSearchEmpleado.setText("SearchEmplado");
        jMenuItemSearchEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSearchEmpleadoActionPerformed(evt);
            }
        });
        menuEmpleado.add(jMenuItemSearchEmpleado);

        ListEmpleado.setText("ListEmpleados");
        ListEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListEmpleadoActionPerformed(evt);
            }
        });
        menuEmpleado.add(ListEmpleado);

        jMenuItemUpdateEmpleados.setText("UpdateEmpleados");
        jMenuItemUpdateEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUpdateEmpleadosActionPerformed(evt);
            }
        });
        menuEmpleado.add(jMenuItemUpdateEmpleados);

        jMenuItemDeleteEmpleado.setText("DeleteEmpleado");
        jMenuItemDeleteEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteEmpleadoActionPerformed(evt);
            }
        });
        menuEmpleado.add(jMenuItemDeleteEmpleado);

        jMenuBar1.add(menuEmpleado);

        menuAyuda.setText("Ayuda");
        menuAyuda.setName("Menu Ayuda"); // NOI18N

        itemAcercaDe.setText("Acerca de ...");
        itemAcercaDe.setName("Opcion Acerca de"); // NOI18N
        itemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(itemAcercaDe);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcercaDeActionPerformed
         JOptionPane.showMessageDialog(this, "Desarrollado por David Alejandro De los Reyes Ostos");
    }//GEN-LAST:event_itemAcercaDeActionPerformed

    private void itemAddEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddEmpleadoActionPerformed
        GUIAddEmpleado gui = new GUIAddEmpleado(this.empleadoServicio);
        gui.setVisible(true);
        
    }//GEN-LAST:event_itemAddEmpleadoActionPerformed

    private void jMenuItemSearchEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSearchEmpleadoActionPerformed
        GUISearchEmpleadoPorNoDocumento gui = new GUISearchEmpleadoPorNoDocumento(this.empleadoServicio);
        gui.setVisible(true);
       
    }//GEN-LAST:event_jMenuItemSearchEmpleadoActionPerformed

    private void ListEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListEmpleadoActionPerformed
        GUIListEmpleados guiListEmpleados = new GUIListEmpleados(this.empleadoServicio);
        guiListEmpleados.setVisible(true);
    }//GEN-LAST:event_ListEmpleadoActionPerformed

    private void jMenuItemUpdateEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUpdateEmpleadosActionPerformed
        GUIActualizarEmpleado guiActualizarEmpleado = new GUIActualizarEmpleado(this.empleadoServicio);
        guiActualizarEmpleado.setVisible(true);
    }//GEN-LAST:event_jMenuItemUpdateEmpleadosActionPerformed

    private void menuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEmpleadoActionPerformed

    private void jMenuItemDeleteEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteEmpleadoActionPerformed
        GUIEliminarEmpleado guiEliminarEmpleado = new GUIEliminarEmpleado(this.empleadoServicio);
        guiEliminarEmpleado.setVisible(true);
    }//GEN-LAST:event_jMenuItemDeleteEmpleadoActionPerformed

    private void jMenuItemGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGenerarReporteActionPerformed
        JOptionPane.showMessageDialog(this, "Proximamente");
    }//GEN-LAST:event_jMenuItemGenerarReporteActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUIPrincipal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ListEmpleado;
    private javax.swing.JMenuItem itemAcercaDe;
    private javax.swing.JMenuItem itemAddEmpleado;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemDeleteEmpleado;
    private javax.swing.JMenuItem jMenuItemGenerarReporte;
    private javax.swing.JMenuItem jMenuItemSearchEmpleado;
    private javax.swing.JMenuItem jMenuItemUpdateEmpleados;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuEmpleado;
    // End of variables declaration//GEN-END:variables
}

